In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt


In [4]:
df=pd.read_csv("https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv")

In [5]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
x=df.iloc[:,:4].values

In [7]:
y=df['species'].values

In [8]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [13]:
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler()

In [15]:
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [16]:
x_train

array([[ 2.10977774e+00, -1.96303850e-01,  1.58766974e+00,
         1.14494827e+00],
       [-8.88485272e-01,  1.66955453e+00, -1.24844783e+00,
        -1.14707051e+00],
       [ 1.74998618e+00, -4.29536147e-01,  1.42083929e+00,
         7.62945138e-01],
       [ 1.03040305e+00, -1.96303850e-01,  6.97907362e-01,
         6.35610762e-01],
       [ 3.10819932e-01, -1.96303850e-01,  4.75466769e-01,
         2.53607633e-01],
       [ 2.22970826e+00,  1.66955453e+00,  1.64327988e+00,
         1.27228264e+00],
       [-8.88485272e-01,  1.66955453e+00, -1.19283768e+00,
        -1.27440488e+00],
       [-1.48813787e+00,  7.36625338e-01, -1.30405798e+00,
        -1.14707051e+00],
       [-1.00841579e+00,  7.36625338e-01, -1.24844783e+00,
        -1.27440488e+00],
       [-2.88832670e-01, -6.62768444e-01,  6.42297214e-01,
         1.01761389e+00],
       [-5.28693711e-01, -1.96303850e-01,  4.19856620e-01,
         3.80942009e-01],
       [-1.68902150e-01, -1.36246533e+00,  6.97907362e-01,
      

In [22]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [24]:
y_pred=classifier.predict(x_test)

In [25]:
y_pred

array(['virginica', 'versicolor', 'setosa', 'setosa', 'versicolor',
       'setosa', 'virginica', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'setosa', 'versicolor',
       'versicolor', 'virginica', 'versicolor', 'versicolor',
       'versicolor', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'setosa'], dtype='<U10')

In [26]:
from sklearn.metrics import confusion_matrix 
cm=confusion_matrix(y_test,y_pred)

In [27]:
from sklearn.metrics import accuracy_score
print("Acc:-",accuracy_score(y_test,y_pred))

Acc:- 0.9333333333333333


In [28]:
print(cm)

[[ 8  0  0]
 [ 0 14  0]
 [ 0  2  6]]


In [29]:
df=pd.DataFrame({"Real Values:":y_test,"Predicted Value:":y_pred})

In [30]:
df

Real Values: Predicted Value:
0     virginica        virginica
1    versicolor       versicolor
2        setosa           setosa
3        setosa           setosa
4    versicolor       versicolor
5        setosa           setosa
6     virginica        virginica
7    versicolor       versicolor
8    versicolor       versicolor
9    versicolor       versicolor
10    virginica        virginica
11   versicolor       versicolor
12   versicolor       versicolor
13       setosa           setosa
14   versicolor       versicolor
15    virginica       versicolor
16    virginica        virginica
17   versicolor       versicolor
18   versicolor       versicolor
19   versicolor       versicolor
20       setosa           setosa
21       setosa           setosa
22       setosa           setosa
23   versicolor       versicolor
24    virginica        virginica
25   versicolor       versicolor
26    virginica        virginica
27   versicolor       versicolor
28    virginica       versicolor
29       setosa           setosa

In [31]:
from sklearn.metrics import precision_score,recall_score

In [34]:
p=precision_score(y_test,y_pred,average="micro")
print(p)
r=recall_score(y_test,y_pred,average="micro")
print(p)

0.9333333333333333
0.9333333333333333


In [35]:
e=1-accuracy_score(y_test,y_pred)
print(e)

0.06666666666666665
