In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

iris = pd.read_csv('./Iris.csv')
X=iris.iloc[:,:4].values
y = iris['species'].values
print(dataset.head(5)) 

KeyError: 'species'

In [2]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

iris = pd.read_csv('./Iris.csv')
X=iris.iloc[:,:4].values
y = iris['Species'].values
print(dataset.head(5)) 

NameError: name 'dataset' is not defined

In [3]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

iris = pd.read_csv('./Iris.csv')
X=iris.iloc[:,:4].values
y = iris['Species'].values
print(iris.head(5)) 

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [5]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


SyntaxError: invalid syntax (514751664.py, line 1)

In [6]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [7]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [8]:
y_pred = classifier.predict(X_test) 

In [9]:
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test, y_pred) 
from sklearn.metrics import accuracy_score
print("Accuracy : ", accuracy_score(y_test, y_pred))
print(cm)

Accuracy :  1.0
[[12  0  0]
 [ 0  8  0]
 [ 0  0 10]]


In [10]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
print(df)

        Real Values Predicted Values
0   Iris-versicolor  Iris-versicolor
1       Iris-setosa      Iris-setosa
2    Iris-virginica   Iris-virginica
3   Iris-versicolor  Iris-versicolor
4    Iris-virginica   Iris-virginica
5       Iris-setosa      Iris-setosa
6    Iris-virginica   Iris-virginica
7    Iris-virginica   Iris-virginica
8    Iris-virginica   Iris-virginica
9   Iris-versicolor  Iris-versicolor
10      Iris-setosa      Iris-setosa
11      Iris-setosa      Iris-setosa
12  Iris-versicolor  Iris-versicolor
13  Iris-versicolor  Iris-versicolor
14   Iris-virginica   Iris-virginica
15      Iris-setosa      Iris-setosa
16  Iris-versicolor  Iris-versicolor
17  Iris-versicolor  Iris-versicolor
18   Iris-virginica   Iris-virginica
19      Iris-setosa      Iris-setosa
20   Iris-virginica   Iris-virginica
21      Iris-setosa      Iris-setosa
22      Iris-setosa      Iris-setosa
23      Iris-setosa      Iris-setosa
24   Iris-virginica   Iris-virginica
25      Iris-setosa      Iris-setosa
2

In [11]:
from sklearn.metrics import precision_score, recall_score, accuracy_score 
m=accuracy_score(y_test, y_pred)
print("error rate:-",1-m) 
print('Precision:',precision_score(y_test,y_pred,average='micro')
print("Recall Score:",recall_score(y_test,y_pred,average='micro'))

SyntaxError: invalid syntax (1625805534.py, line 5)

In [12]:
from sklearn.metrics import precision_score, recall_score, accuracy_score 
m=accuracy_score(y_test, y_pred)
print("error rate:-",1-m) 
print('Precision:',precision_score(y_test,y_pred,average='micro'))
print("Recall Score:",recall_score(y_test,y_pred,average='micro'))

error rate:- 0.0
Precision: 1.0
Recall Score: 1.0
